import { ICourse } from "@/types/course.type";


export const courses: ICourse[] = [
  {
    id: 1,
    title: "Web Development Fundamentals",
    description: "Learn the basics of HTML, CSS, and JavaScript",
    category: "Web Development",
    level: "Beginner",
    price: 49.99,
    rating: 4.8,
    students: 15420,
    image: "/web-development-course.png",
    instructor: "John Smith",
    duration: "8 weeks",
  },
  {
    id: 2,
    title: "React Advanced Patterns",
    description: "Master advanced React concepts and patterns",
    category: "Web Development",
    level: "Advanced",
    price: 79.99,
    rating: 4.9,
    students: 8932,
    image: "/react-programming.png",
    instructor: "Sarah Johnson",
    duration: "10 weeks",
  },
  {
    id: 3,
    title: "Python for Data Science",
    description: "Learn Python and data analysis with pandas and numpy",
    category: "Data Science",
    level: "Intermediate",
    price: 69.99,
    rating: 4.7,
    students: 22150,
    image: "/python-data-science.png",
    instructor: "Mike Chen",
    duration: "12 weeks",
  },
  {
    id: 4,
    title: "UI/UX Design Masterclass",
    description: "Create beautiful and functional user interfaces",
    category: "Design",
    level: "Beginner",
    price: 59.99,
    rating: 4.6,
    students: 11200,
    image: "/ui-ux-design-concept.png",
    instructor: "Emma Wilson",
    duration: "6 weeks",
  },
  {
    id: 5,
    title: "Machine Learning Basics",
    description: "Introduction to ML algorithms and applications",
    category: "Data Science",
    level: "Intermediate",
    price: 89.99,
    rating: 4.8,
    students: 9876,
    image: "/machine-learning-concept.png",
    instructor: "Dr. Alex Kumar",
    duration: "14 weeks",
  },
  {
    id: 6,
    title: "Mobile App Development",
    description: "Build iOS and Android apps with React Native",
    category: "Mobile Development",
    level: "Intermediate",
    price: 74.99,
    rating: 4.7,
    students: 13450,
    image: "/mobile-app-development.png",
    instructor: "James Brown",
    duration: "10 weeks",
  },
  {
    id: 7,
    title: "Cloud Computing with AWS",
    description: "Deploy and manage applications on AWS",
    category: "Cloud",
    level: "Advanced",
    price: 99.99,
    rating: 4.9,
    students: 7654,
    image: "/aws-cloud-computing.jpg",
    instructor: "Lisa Anderson",
    duration: "12 weeks",
  },
  {
    id: 8,
    title: "Digital Marketing Essentials",
    description: "Master SEO, SEM, and social media marketing",
    category: "Marketing",
    level: "Beginner",
    price: 44.99,
    rating: 4.5,
    students: 18900,
    image: "/digital-marketing-strategy.png",
    instructor: "Rachel Green",
    duration: "8 weeks",
  },
  {
    id: 9,
    title: "Blockchain Development",
    description: "Build decentralized applications with Solidity",
    category: "Blockchain",
    level: "Advanced",
    price: 109.99,
    rating: 4.8,
    students: 5432,
    image: "/blockchain-development.png",
    instructor: "David Lee",
    duration: "16 weeks",
  },
];
