import { ICourse } from "@/types/course.type";
import web from "@/assets/web.jpg";
import react from "@/assets/react.png";
import python from "@/assets/python.jpg";
import ui from "@/assets/ui.jpg";
import machine from "@/assets/machine.jpg";
import mobile from "@/assets/mobile.jpg";
import cloud from "@/assets/cloud.jpg";
import digital from "@/assets/digital.jpg";
import block from "@/assets/block.jpg";
import game from "@/assets/game.jpg";
import ai from "@/assets/ai.jpg";

export const courses: ICourse[] = [
  {
    id: 1,
    title: "Web Development Fundamentals",
    description: "Learn the basics of HTML, CSS, and JavaScript",
    category: "Web Development",
    level: "Beginner",
    price: 49.99,
    rating: 4.8,
    students: 15420,
    image: web,
    instructor: "John Smith",
    duration: "8 weeks",
  },
  {
    id: 2,
    title: "React Advanced Patterns",
    description: "Master advanced React concepts and patterns",
    category: "Web Development",
    level: "Advanced",
    price: 79.99,
    rating: 4.9,
    students: 8932,
    image: react,
    instructor: "Sarah Johnson",
    duration: "10 weeks",
  },
  {
    id: 3,
    title: "Python for Data Science",
    description: "Learn Python and data analysis with pandas and numpy",
    category: "Data Science",
    level: "Intermediate",
    price: 69.99,
    rating: 4.7,
    students: 22150,
    image: python,
    instructor: "Mike Chen",
    duration: "12 weeks",
  },
  {
    id: 4,
    title: "UI/UX Design Masterclass",
    description: "Create beautiful and functional user interfaces",
    category: "Design",
    level: "Beginner",
    price: 59.99,
    rating: 4.6,
    students: 11200,
    image: ui,
    instructor: "Emma Wilson",
    duration: "6 weeks",
  },
  {
    id: 5,
    title: "Machine Learning Basics",
    description: "Introduction to ML algorithms and applications",
    category: "Data Science",
    level: "Intermediate",
    price: 89.99,
    rating: 4.8,
    students: 9876,
    image: machine,
    instructor: "Dr. Alex Kumar",
    duration: "14 weeks",
  },
  {
    id: 6,
    title: "Mobile App Development",
    description: "Build iOS and Android apps with React Native",
    category: "Mobile Development",
    level: "Intermediate",
    price: 74.99,
    rating: 4.7,
    students: 13450,
    image: mobile,
    instructor: "James Brown",
    duration: "10 weeks",
  },
  {
    id: 7,
    title: "Cloud Computing with AWS",
    description: "Deploy and manage applications on AWS",
    category: "Cloud",
    level: "Advanced",
    price: 99.99,
    rating: 4.9,
    students: 7654,
    image: cloud,
    instructor: "Lisa Anderson",
    duration: "12 weeks",
  },
  {
    id: 8,
    title: "Digital Marketing Essentials",
    description: "Master SEO, SEM, and social media marketing",
    category: "Marketing",
    level: "Beginner",
    price: 44.99,
    rating: 4.5,
    students: 18900,
    image: digital,
    instructor: "Rachel Green",
    duration: "8 weeks",
  },
  {
    id: 9,
    title: "Blockchain Development",
    description: "Build decentralized applications with Solidity",
    category: "Blockchain",
    level: "Advanced",
    price: 109.99,
    rating: 4.8,
    students: 5432,
    image: block,
    instructor: "David Lee",
    duration: "16 weeks",
  },
  // --- 30 new courses below ---
  {
    id: 10,
    title: "Full Stack Web Development",
    description: "Combine frontend and backend skills to build full apps",
    category: "Web Development",
    level: "Advanced",
    price: 99.99,
    rating: 4.9,
    students: 17800,
    image: web,
    instructor: "Olivia Harris",
    duration: "14 weeks",
  },
  {
    id: 11,
    title: "React Hooks Deep Dive",
    description: "Understand and apply all major React hooks effectively",
    category: "Web Development",
    level: "Intermediate",
    price: 64.99,
    rating: 4.7,
    students: 9400,
    image: react,
    instructor: "Daniel Carter",
    duration: "8 weeks",
  },
  {
    id: 12,
    title: "Data Visualization with Python",
    description: "Create interactive charts and dashboards using Python",
    category: "Data Science",
    level: "Intermediate",
    price: 74.99,
    rating: 4.6,
    students: 10300,
    image: python,
    instructor: "Sophia Patel",
    duration: "9 weeks",
  },
  {
    id: 13,
    title: "Advanced UI Animation Techniques",
    description: "Design smooth and engaging UI animations in Figma",
    category: "Design",
    level: "Advanced",
    price: 69.99,
    rating: 4.8,
    students: 8120,
    image: ui,
    instructor: "Henry Brooks",
    duration: "7 weeks",
  },
  {
    id: 14,
    title: "Deep Learning with TensorFlow",
    description: "Train neural networks for image and text recognition",
    category: "AI",
    level: "Advanced",
    price: 119.99,
    rating: 4.9,
    students: 9870,
    image: machine,
    instructor: "Dr. Maria Lopez",
    duration: "16 weeks",
  },
  {
    id: 15,
    title: "Cybersecurity Fundamentals",
    description: "Learn network security, encryption, and ethical hacking",
    category: "Cybersecurity",
    level: "Beginner",
    price: 84.99,
    rating: 4.7,
    students: 12100,
    image: ai,
    instructor: "Ethan Walker",
    duration: "10 weeks",
  },
  {
    id: 16,
    title: "Game Development with Unity",
    description: "Create your first 2D and 3D games using Unity engine",
    category: "Game Development",
    level: "Beginner",
    price: 79.99,
    rating: 4.8,
    students: 11000,
    image: game,
    instructor: "Nathan Moore",
    duration: "12 weeks",
  },
  {
    id: 17,
    title: "Backend Engineering with Node.js",
    description: "Learn to build RESTful APIs and microservices",
    category: "Backend Development",
    level: "Intermediate",
    price: 89.99,
    rating: 4.8,
    students: 9700,
    image: react,
    instructor: "Ava Davis",
    duration: "10 weeks",
  },
  {
    id: 18,
    title: "Cloud Infrastructure with Google Cloud",
    description: "Master Google Cloud Platform for scalable deployments",
    category: "Cloud",
    level: "Advanced",
    price: 99.99,
    rating: 4.8,
    students: 7650,
    image: cloud,
    instructor: "William Clark",
    duration: "12 weeks",
  },
  {
    id: 19,
    title: "Marketing Analytics with Python",
    description: "Use Python to analyze and optimize digital campaigns",
    category: "Marketing",
    level: "Intermediate",
    price: 69.99,
    rating: 4.6,
    students: 9300,
    image: digital,
    instructor: "Emily Parker",
    duration: "9 weeks",
  },
  {
    id: 20,
    title: "AI-Powered Chatbot Development",
    description: "Build chatbots using NLP and Python",
    category: "AI",
    level: "Advanced",
    price: 114.99,
    rating: 4.9,
    students: 8800,
    image: machine,
    instructor: "Dr. Hassan Rahman",
    duration: "14 weeks",
  },
  {
    id: 21,
    title: "Responsive Web Design",
    description: "Design flexible layouts for all screen sizes",
    category: "Web Development",
    level: "Beginner",
    price: 54.99,
    rating: 4.7,
    students: 14500,
    image: web,
    instructor: "Grace Evans",
    duration: "6 weeks",
  },
  {
    id: 22,
    title: "React Native for Beginners",
    description: "Develop mobile apps with React Native from scratch",
    category: "Mobile Development",
    level: "Beginner",
    price: 69.99,
    rating: 4.7,
    students: 9100,
    image: mobile,
    instructor: "Noah White",
    duration: "9 weeks",
  },
  {
    id: 23,
    title: "UI Wireframing & Prototyping",
    description: "Learn how to create intuitive design prototypes",
    category: "Design",
    level: "Intermediate",
    price: 59.99,
    rating: 4.5,
    students: 7300,
    image: ui,
    instructor: "Charlotte King",
    duration: "7 weeks",
  },
  {
    id: 24,
    title: "Introduction to SQL & Databases",
    description: "Understand SQL queries and relational databases",
    category: "Backend Development",
    level: "Beginner",
    price: 49.99,
    rating: 4.6,
    students: 12800,
    image: python,
    instructor: "Benjamin Carter",
    duration: "8 weeks",
  },
  {
    id: 25,
    title: "DevOps with Docker and Kubernetes",
    description: "Automate deployment pipelines and scaling systems",
    category: "DevOps",
    level: "Advanced",
    price: 109.99,
    rating: 4.9,
    students: 8400,
    image: cloud,
    instructor: "Lucas Martin",
    duration: "14 weeks",
  },
  {
    id: 26,
    title: "Data Engineering with Python",
    description: "Build robust ETL pipelines and data workflows",
    category: "Data Science",
    level: "Advanced",
    price: 99.99,
    rating: 4.8,
    students: 7200,
    image: python,
    instructor: "Harper Allen",
    duration: "13 weeks",
  },
  {
    id: 27,
    title: "AR & VR App Development",
    description: "Create immersive augmented and virtual experiences",
    category: "AR/VR",
    level: "Advanced",
    price: 119.99,
    rating: 4.9,
    students: 5600,
    image: mobile,
    instructor: "Elijah Thompson",
    duration: "15 weeks",
  },
  {
    id: 28,
    title: "Digital Branding & Strategy",
    description: "Learn how to build and scale a digital brand",
    category: "Marketing",
    level: "Intermediate",
    price: 64.99,
    rating: 4.5,
    students: 8900,
    image: digital,
    instructor: "Madison Rivera",
    duration: "8 weeks",
  },
  {
    id: 29,
    title: "Next.js for Production",
    description: "Build SEO-friendly and performant React apps",
    category: "Web Development",
    level: "Advanced",
    price: 89.99,
    rating: 4.9,
    students: 9700,
    image: react,
    instructor: "Oliver Murphy",
    duration: "11 weeks",
  },
  {
    id: 30,
    title: "AI Ethics and Responsible ML",
    description: "Understand the principles of ethical AI development",
    category: "AI",
    level: "Intermediate",
    price: 79.99,
    rating: 4.7,
    students: 6100,
    image: machine,
    instructor: "Dr. Priya Nair",
    duration: "9 weeks",
  },
  {
    id: 31,
    title: "Blockchain for Business",
    description: "Use blockchain for supply chain, banking, and more",
    category: "Blockchain",
    level: "Intermediate",
    price: 99.99,
    rating: 4.8,
    students: 6400,
    image: block,
    instructor: "Samuel Ortiz",
    duration: "12 weeks",
  },
  {
    id: 32,
    title: "Intro to Ethical Hacking",
    description: "Discover how hackers exploit systems and defend them",
    category: "Cybersecurity",
    level: "Intermediate",
    price: 94.99,
    rating: 4.8,
    students: 9500,
    image: cloud,
    instructor: "Isabella Cruz",
    duration: "10 weeks",
  },
  {
    id: 33,
    title: "Game Physics & Animation",
    description: "Learn physics and animation systems in Unity",
    category: "Game Development",
    level: "Advanced",
    price: 89.99,
    rating: 4.9,
    students: 7200,
    image: mobile,
    instructor: "Mason Walker",
    duration: "13 weeks",
  },
  {
    id: 34,
    title: "Design Systems in Figma",
    description: "Create scalable and reusable UI components",
    category: "Design",
    level: "Advanced",
    price: 74.99,
    rating: 4.8,
    students: 9800,
    image: ui,
    instructor: "Ella Foster",
    duration: "8 weeks",
  },
  {
    id: 35,
    title: "Serverless Apps with AWS Lambda",
    description: "Deploy scalable APIs without managing servers",
    category: "Cloud",
    level: "Advanced",
    price: 109.99,
    rating: 4.9,
    students: 6500,
    image: cloud,
    instructor: "Jack Nelson",
    duration: "12 weeks",
  },
  {
    id: 36,
    title: "AI for Game Developers",
    description: "Implement AI logic for NPCs and game mechanics",
    category: "AI",
    level: "Advanced",
    price: 119.99,
    rating: 4.9,
    students: 5800,
    image: machine,
    instructor: "Dr. Naomi Kim",
    duration: "14 weeks",
  },
  {
    id: 37,
    title: "React Performance Optimization",
    description: "Boost React app performance with advanced techniques",
    category: "Web Development",
    level: "Advanced",
    price: 84.99,
    rating: 4.8,
    students: 9200,
    image: react,
    instructor: "Jacob Martinez",
    duration: "9 weeks",
  },
  {
    id: 38,
    title: "NoSQL Databases with MongoDB",
    description: "Build flexible data models using MongoDB",
    category: "Backend Development",
    level: "Intermediate",
    price: 74.99,
    rating: 4.7,
    students: 8800,
    image: python,
    instructor: "Chloe Bennett",
    duration: "10 weeks",
  },
  {
    id: 39,
    title: "Creative Copywriting for Marketers",
    description: "Master the art of persuasive digital copywriting",
    category: "Marketing",
    level: "Beginner",
    price: 49.99,
    rating: 4.6,
    students: 12300,
    image: digital,
    instructor: "Ryan Mitchell",
    duration: "6 weeks",
  },
];
